
version: 0.1
phases:
  install:
    commands:
      - npm install
      - aws cloudformation package --template-file template.yaml --s3-bucket ppl-lambda-example 
                                   --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - NewSamTemplate.yaml
